// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaleGz.Infrastructure.Persistence;

#nullable disable

namespace SaleGz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526144918_AddTipoEntidadToClientes")]
    partial class AddTipoEntidadToClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaleGz.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Credito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntidad")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CompraId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CompraDetalle", b =>
                {
                    b.Property<int>("CompraDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraDetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompraDetalleId");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CompraDetalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Consumo", b =>
                {
                    b.Property<int>("ConsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumoId"));

                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.HasKey("ConsumoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.ConsumoGasto", b =>
                {
                    b.Property<int>("ConsumosGastosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumosGastosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConsumosGastosId");

                    b.ToTable("ConsumosGastos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Control", b =>
                {
                    b.Property<int>("ControlesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ControlesId"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaLimiteConsumo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteFiscal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteGubernamental")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteRegimenEspecial")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ITBS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItbsCalculo")
                        .HasColumnType("int");

                    b.Property<int>("LimiteConteoConsumo")
                        .HasColumnType("int");

                    b.Property<int>("LimiteConteoFiscal")
                        .HasColumnType("int");

                    b.Property<int>("LimiteConteoGubernamental")
                        .HasColumnType("int");

                    b.Property<int>("LimiteConteoRegimenEspecial")
                        .HasColumnType("int");

                    b.Property<int>("LimiteDiaPago")
                        .HasColumnType("int");

                    b.Property<bool>("MostrarDireccionCliente")
                        .HasColumnType("bit");

                    b.Property<bool>("MostrarTelefonoCliente")
                        .HasColumnType("bit");

                    b.Property<int>("NumOrden")
                        .HasColumnType("int");

                    b.Property<int>("TamanoFactura")
                        .HasColumnType("int");

                    b.Property<int>("TipoOrden")
                        .HasColumnType("int");

                    b.HasKey("ControlesId");

                    b.ToTable("Controles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cotizacion", b =>
                {
                    b.Property<int>("CotizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CotizacionId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ITBIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CotizacionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CotizacionDetalle", b =>
                {
                    b.Property<int>("CotizacionDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CotizacionDetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ITBIS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CotizacionDetalleId");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("CotizacionDetalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cuadre", b =>
                {
                    b.Property<int>("CuadreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuadreId"));

                    b.Property<int>("CantidadCheque")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTarjeta")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTransaccion")
                        .HasColumnType("int");

                    b.Property<decimal>("Diferencia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoCuadre")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FondoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoraApertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("P1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P100")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P1000")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P200")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P2000")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P25")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P50")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P500")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCheque")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTarjeta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTransaccion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("VentasSistema")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CuadreId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cuadres");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CuentaPorCobrarDetalle", b =>
                {
                    b.Property<int>("CuentaPorCobrarDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaPorCobrarDetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CuentaPorCobrarDetalleId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentasPorCobrar");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CuentaPorPagarDetalle", b =>
                {
                    b.Property<int>("CuentaPorPagarDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuentaPorPagarDetalleId"));

                    b.Property<int>("CompraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CuentaPorPagarDetalleId");

                    b.HasIndex("CompraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentasPorPagar");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<decimal>("Exento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Gravado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ITBS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOrden")
                        .HasColumnType("int");

                    b.Property<decimal>("Pagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RncCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tarjeta")
                        .HasColumnType("bit");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("int");

                    b.Property<int>("TipoFactura")
                        .HasColumnType("int");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.FacturaDetalle", b =>
                {
                    b.Property<int>("FacturaDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaDetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ITBS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("RncCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FacturaDetalleId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Fiscal", b =>
                {
                    b.Property<int>("FiscalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiscalId"));

                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.HasKey("FiscalId");

                    b.HasIndex("FacturaId");

                    b.ToTable("Fiscals");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Gasto", b =>
                {
                    b.Property<int>("GastosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("GastosId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.GastoDetalle", b =>
                {
                    b.Property<int>("GastosDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastosDetalleId"));

                    b.Property<int>("ConsumoGastoConsumosGastosId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumosGastosId")
                        .HasColumnType("int");

                    b.Property<int>("GastosId")
                        .HasColumnType("int");

                    b.Property<int>("GastosId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GastosDetalleId");

                    b.HasIndex("ConsumoGastoConsumosGastosId");

                    b.HasIndex("GastosId1");

                    b.ToTable("GastoDetalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Gubernamental", b =>
                {
                    b.Property<int>("GubernamentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GubernamentalId"));

                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.HasKey("GubernamentalId");

                    b.HasIndex("FacturaId");

                    b.ToTable("Gubernamentales");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("Fecha");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inv_Movimientos", (string)null);
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.NotaCredito", b =>
                {
                    b.Property<int>("NotaCreditoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaCreditoId"));

                    b.Property<string>("Comprobante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<string>("EstadoComprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RazonModificacion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NotaCreditoId");

                    b.HasIndex("FacturaId");

                    b.ToTable("NotaCreditos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.NotaCreditoDetalle", b =>
                {
                    b.Property<int>("NotaCreditoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaCreditoDetalleId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Itbis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NotaCreditoId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NotaCreditoDetalleId");

                    b.HasIndex("NotaCreditoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("NotaCreditoDetalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ITBIS")
                        .HasColumnType("int");

                    b.Property<int>("Minimo")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referencia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.RegimenEspecial", b =>
                {
                    b.Property<int>("RegimenEspecialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegimenEspecialId"));

                    b.Property<int>("Conteo")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.HasKey("RegimenEspecialId");

                    b.HasIndex("FacturaId");

                    b.ToTable("RegimenesEspeciales");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.Property<int>("UsuarioPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioPermisoId"));

                    b.Property<bool>("CancelarFacturas")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearClientes")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearCompras")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearCotizaciones")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearCuadres")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearFacturas")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearGastos")
                        .HasColumnType("bit");

                    b.Property<bool>("CrearInventario")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool>("VerClientes")
                        .HasColumnType("bit");

                    b.Property<bool>("VerCompras")
                        .HasColumnType("bit");

                    b.Property<bool>("VerCotizaciones")
                        .HasColumnType("bit");

                    b.Property<bool>("VerCuadres")
                        .HasColumnType("bit");

                    b.Property<bool>("VerFacturas")
                        .HasColumnType("bit");

                    b.Property<bool>("VerGastos")
                        .HasColumnType("bit");

                    b.Property<bool>("VerInventario")
                        .HasColumnType("bit");

                    b.Property<bool>("VerProductos")
                        .HasColumnType("bit");

                    b.Property<bool>("VerReportes")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioPermisoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioPermisos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Compra", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CompraDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Consumo", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cotizacion", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CotizacionDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Cotizacion", "Cotizacion")
                        .WithMany("Detalles")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cuadre", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CuentaPorCobrarDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.CuentaPorPagarDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Compra", "Compra")
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Factura", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.FacturaDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Fiscal", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Gasto", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.GastoDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.ConsumoGasto", "ConsumoGasto")
                        .WithMany()
                        .HasForeignKey("ConsumoGastoConsumosGastosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Gasto", "Gasto")
                        .WithMany("Detalles")
                        .HasForeignKey("GastosId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumoGasto");

                    b.Navigation("Gasto");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Gubernamental", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.NotaCredito", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.NotaCreditoDetalle", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.NotaCredito", "NotaCredito")
                        .WithMany()
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleGz.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaCredito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.RegimenEspecial", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("SaleGz.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Cotizacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SaleGz.Domain.Entities.Gasto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
